### ISSUE TITLE
Possibility to backup PingDirectory data

### ISSUE THREAD

**Issue by DominikStark** [pingidentity/helm-charts#115]
Is there currently a way with this helm chart to get in a k8s job that does backups to a given destination? Like we have it here in the aws k8s files https://github.com/pingidentity/ping-cloud-base/blob/master/k8s-configs/ping-cloud/base/pingdirectory/server/aws/backup.yaml ?

Or what is the common way of doing a backup of the PingDirectory data in k8s?

Great Regards
Dominik

**Comment by samir-gandhi** [comment]
Right, there isn't a way currently, but helm may be the right format to begin adding in backup features like this. 
The recently added [helm test framework](https://helm.pingidentity.com/release-notes/#release-059-may-10-2021) (in beta) may be a good initial candidate for this until an actual backup cronjob is added

**Comment by henryrecker-pingidentity** [comment]
We have an example on the docs page of a periodic PingDirectory backup via a sidecar - https://helm.pingidentity.com/examples/
The details of where the backups are stored are not implemented.
