### ISSUE TITLE
PF Admin login failure 

### ISSUE THREAD

**Issue by gmorgan-ping** [pingidentity/helm-charts#172]
Helm Chart Version: 0.6.6
PF Image: 2106
PF Version: 10.3

When using helm charts, ingress and a PingFederate image tag 2106, users are unable to login successfully to the PF admin console.

The login page renders successfully but the login redirects back to localhost instead of the ingress URL.

It appears in PF 10.3 that the PF **pf.admin.hostname** variable found within run.properties is now deprecated. The new variable in 10.3 is **pf.admin.baseurl**

**Workaround**
In your helm values file, set a global PF_ADMIN_PUBLIC_BASEURL variable.

EG.
global:
  envs:
    PF_ADMIN_PUBLIC_BASEURL: https://mypfadmin.mydomain.com

**Comment by tsigle** [comment]
@gmorgan-ping and I talked and agreed that the variable pf.admin.baseurl in the run.properties should be build based on the existing variables available PF_ADMIN_PUBLIC_HOSTNAME and PF_ADMIN_PUBLIC_PORT_HTTPS.  Something like:

```
pf.admin.baseurl=https://${PF_ADMIN_PUBLIC_HOSTNAME}:${PF_ADMIN_PUBLIC_PORT_HTTPS}
```
