### ISSUE TITLE
Support shareProcessNamespace in pod spec

### ISSUE THREAD

**Issue by henryrecker-pingidentity** [pingidentity/helm-charts#229]
A PingDirectory utility sidecar container needs to share the process namespace with the main PingDirectory container running in the same pod in order to get useful output out of tools like jps. Currently the Helm chart doesn't support setting this field, we should update it to support it.

**Comment by samir-gandhi** [comment]
Could you expand on this? The chart does support sidecar containers in the same pod and optionally file paths. But perhaps something more is needed here?
