### ISSUE TITLE
Ingress - `semverCompare` is not getting the correct k8s version. 

### ISSUE THREAD

**Issue by topijag** [pingidentity/helm-charts#235]
On the ingress template, `semverCompare` is not working as aspected on K8s >1.18.
https://github.com/pingidentity/helm-charts/blob/master/charts/ping-devops/templates/pinglib/_ingress.tpl#L7-L11

```
{{- if semverCompare ">1.18" $top.Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1
{{- else }}
apiVersion: networking.k8s.io/v1beta1
{{- end }}

```
I'm still getting :
`apiVersion: networking.k8s.io/v1beta1` instead of `apiVersion: networking.k8s.io/v1`

I'm not sure if this is a bug of `semverCompare` or something else.

Version of Helm and Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:58:09Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

```
helm version
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"dirty", GoVersion:"go1.16.5"}
```

version of the chart: 
`0.7.8`

Example that might help on solving this:
https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-16.5.0/charts/kube-prometheus-stack/templates/_helpers.tpl#L106
and
https://github.com/prometheus-community/helm-charts/blob/kube-prometheus-stack-16.5.0/charts/kube-prometheus-stack/templates/_helpers.tpl#L123

**Comment by jjustinic** [comment]
I think it's having issue with the handling of the version there that includes the `+`. It does work when the version is just `1.19` instead of `1.19+`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.12", GitCommit:"2cb4598553d0a2ca5f3eb7980c99cd8236cc5011", GitTreeState:"clean", BuildDate:"2021-06-16T13:00:29Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"d062c7ef8a88e89e5f28f1c1146bd707d00d4881", GitTreeState:"clean", BuildDate:"2021-11-01T16:41:06Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

I'm not sure in this case version really matters though. I would think just checking for the availability of the stable `v1` over `v1beta1` would be good enough. I don't get a say though. This was just added in response to my issue #175.

**Comment by wesleymccollam** [comment]
@topijag I've made changes in [this commit](https://github.com/pingidentity/helm-charts/commit/630b133f126676cc4effdea51597214ba00ec4e0). Would you mind verifying if this change works locally for you? If you clone the dev branch, you can run a command pointing to your local charts (below).

`helm upgrade --install <release name> charts/ping-devops -f <.yaml>`

**Comment by topijag** [comment]
Thanks @wesleymccollam for the change, I'll test it!
I'm facing this as well, https://github.com/kubernetes/kubernetes/issues/94761#issuecomment-691982480

Despite the fact of using the proper apiVersion, the deprecated one is still being seen as the the default one 🤦

**Comment by wesleymccollam** [comment]
@topijag, I've added another commit that should take care of the warning message. The template code was checking against 1.18.x instead of 1.19.x for the Kubernetes Version.

**Comment by topijag** [comment]
It looks like this is missing in:

```
-{{- if semverCompare ">=1.19.x" $top.Capabilities.KubeVersion }}
+{{- if semverCompare ">=1.19.x" $top.Capabilities.KubeVersion.Version }}
```
https://github.com/pingidentity/helm-charts/blob/dev/charts/ping-devops/templates/pinglib/_ingress.tpl#L7

**Comment by wesleymccollam** [comment]
@topijag, excellent catch. I've updated this for the next release which should go out later today or tomorrow.
