### ISSUE TITLE
Unable to download Helm Chart 0.9.7 from terraform

### ISSUE THREAD

**Issue by srikanth2302** [pingidentity/helm-charts#270]
From Yesterday, I have seen the issue that i'm unable to download helm chart of 0.9.7 as it is searching in 0.9.8 folder
resource "helm_release" "pinghelm" {
  name  					      = "pingfed"
  repository 			              = "https://kubernetes.github.io/ingress-nginx"
  chart 					      = "ping-devops"
  version    				      = "0.9.7"
}

Error:
Error: failed to download "https://github.com/pingidentity/helm-charts/releases/download/ping-devops-0.9.8/ping-devops-0.9.7.tgz" at version "0.9.7"

**Comment by henryrecker-pingidentity** [comment]
@srikanth2302 Thank you for opening this issue. We've pushed a fix that should allow you to download version 0.9.7 again.
