### ISSUE TITLE
SemVer selecting autoscaling/v2beta2 rather than autoscaling/v2

### ISSUE THREAD

**Issue by mwhittlestone2** [pingidentity/helm-charts#280]
Following upgrade of k8s to 1.26
(kubernetes version number reported by AWS (EKS) is v1.26.10-eks-4f4795d)

apiVersion being set to autoscaling/v2beta2 - should be autoscaling/v2

See also: 
https://github.com/pingidentity/helm-charts/issues/278
https://github.com/pingidentity/helm-charts/issues/235

helm-charts/charts/ping-devops/templates/pinglib/_hpa.tpl 
lines 4-8
{{- if semverCompare ">1.22" $top.Capabilities.KubeVersion.Version }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}

A proposed fix for the pingidentity helm chart could be to use a better, more specific feature 
support flag:
{{- if $top.Capabilities.APIVersions.Has "autoscaling/v2" }}

**Comment by PingDavidR** [comment]
Thanks, Mike!  We've dropped a ticket to take a look, but on the surface seems to be a simple enhancement for the charts.  Thanks for your input, and we'll track progress here as we move it through the pipeline.

**Comment by henryrecker-pingidentity** [comment]
We've pushed the change described here and we'll be putting out a release in the next couple weeks that will include that change.

**Comment by bhargava1812** [comment]
Is this feature released?

**Comment by erikostien-pingidentity** [comment]
Absolutely! Our release cycle for non-security updates is the first week of each month.  Check this page https://github.com/pingidentity/helm-charts/releases to see when a release is made and what changes were made.

**Comment by PingDavidR** [comment]
in addition, you can check here for any changes made: https://helm.pingidentity.com/release-notes/previousReleases/
