### ISSUE TITLE
upgrade to version 10

### ISSUE THREAD

**Issue by cellison** [pingidentity/helm-charts#283]
When I ran the "helm repo update" the charts where updated to 0.10.0 from 0.9.10.  

Running: helm upgrade --install myping pingidentity/ping-devops -f ./30-helm/simple-sync.yaml -f ./ingress.yaml
Resulted in the following message.
Release "myping" does not exist. Installing it now.
Error: template: ping-devops/templates/pingdirectory/ingress.yaml:2:4: executing "ping-devops/templates/pingdirectory/ingress.yaml" at <include "pinglib.ingress" (list . "pingdirectory")>: error calling include: template: ping-devops/templates/pinglib/_ingress.tpl:56:6: executing "pinglib.ingress" at <include "pinglib.merge.templates" (append . "ingress")>: error calling include: template: ping-devops/templates/pinglib/_merge-util.tpl:26:30: executing "pinglib.merge.templates" at <include $baseTemplate $paramList>: error calling include: template: ping-devops/templates/pinglib/_ingress.tpl:19:11: executing "pinglib.ingress.tpl" at ...

This was verified on multiple servers

Installing the previous version worked:
helm upgrade --install myping pingidentity/ping-devops --version v0.9.22

If no helm export so maybe there is something I need to do when moving to 0.10 but I didn't see anything in the notes.  The fact that I can install any of the 0.9.x versions but the latest version has an issue leads me to think its the charts.  
Also the date on 0.10.0 should probably be 2024?
Regards,
Chris

**Comment by PingDavidR** [comment]
Thanks @cellison I'll drop a ticket to investigate further.  Something is not kosher with the latest release - thanks for letting us know!

**Comment by PingDavidR** [comment]
@cellison The changes were noted in the Helm chart revisions but not captured in our examples on the DevOps portal.

If you will modify your ingress.yaml file to have this at the end, removing the ingress.class line from the annotations and adding the spec.ingressClassName, things should work

`global:`
`  envs:`
`    PING_IDENTITY_ACCEPT_EULA: "YES"`
`  ingress:`
`    enabled: true`
`    addReleaseNameToHost: prepend`
`    defaultDomain: "insert domain name here"`
`    defaultTlsSecret:`
`    annotations:`
`      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"`
`    spec:`
`      ingressClassName: nginx-public`
