### ISSUE TITLE
Possible value switch to enable/disable curl initcontainer on PingFederate engine

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/helm-charts#30]
In environments where the curl docker image is not available (or not yet approved for use), it may be useful to have a values parameter to switch the curl initcontainer for PingFederate engine on or off, to use a wait-for command on the main container instead

**Comment by tsigle** [comment]
This is a good point, and timely, as we are looking at an enhancement to the wait-for command.  Will take a look at this.
