### ISSUE TITLE
Default ingress annotations on global cannot be overridden

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/helm-charts#31]
The current annotations for the global ingress are set as follows

https://github.com/pingidentity/helm-charts/blob/9f5b096600279c835b91b7fb91ca90754ea0e5a8/charts/ping-devops/values.yaml#L39-L41

We have found that if these are not appropriate for the environment and we need to have our own ingress annotations block, these pre-seeded annotations are mixed with the new ones, causing failure.
E.g, if we set the following in our values file (notice we've removed the ingress class and changed the name of backend-protocol annotation):
```
annotations:
      ingress.kubernetes.io/backend-protocol: HTTPS
```
we get the resulting definition, which causes a failed ingress:
```
│ Annotations:                     ingress.kubernetes.io/backend-protocol: HTTPS                                    │
│                                  kubernetes.io/ingress.class: nginx-public                                        │
│                                  meta.helm.sh/release-name: [obscured]                                                │
│                                  meta.helm.sh/release-namespace: [obscured]             │
│                                  nginx.ingress.kubernetes.io/backend-protocol: HTTPS                              │
```

It may be best to unset the default annotations as such:
```
annotations: {}
    #  nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    #  kubernetes.io/ingress.class: "nginx-public"
```

**Comment by tsigle** [comment]
@patrickcping and I talked and agreed that we should take these default annotations out and provide documentation around this, should the deployer be using the nginx controller.

**Comment by tsigle** [comment]
Close with release 0.3.2
