### ISSUE TITLE
Enable creation of a non-default service account for the workload

### ISSUE THREAD

**Issue by jjustinic** [pingidentity/helm-charts#87]
Currently, pods use either the default service account or, if Vault is enabled, the service account name configured for Vault. However, the chart does not have the ability to create this service account and requires that it has been created externally. In a cluster where workloads are separated by namespace, there would not be a named service account in the namespace to use for Vault. Ideally, I would like the ability for the release to create a named service account for the workload rather than requiring additional setup for the workload on the cluster side.

**Comment by tsigle** [comment]
@jjustinic Isn't the service account created 1 time for the namespace?  Are you asking for the ability to customize the annotation "vault.hashicorp.com/service"?

If you could provide an example of what values.yaml you'd like to include and how that would be reflected in the annotations.

As far as serviceAccount, isn't that created once, for example, when a namespace is created?

**Comment by jjustinic** [comment]
I think I can best describe it by referencing what happens in the Vault Helm chart for a complete picture.

When Vault is installed, it creates a couple service accounts in the namespace it is installed in. The first is used by the Vault Agent Injector pod, which is a mutating webhook controller. This service account is granted numerous permissions because it effectively has to add to and modify whatever comes in. Second, another service account is created for the Vault server. This service account only needs to validate other service accounts, so the permissions are limited to the `TokenReview` API. Effectively, each workload that runs has a different identity / service account that can be assigned only the permissions required. It never uses the default service account for anything and creates one to represent each unique workload.

When I run a workload, such as PingFederate and PingDirectory, I really want the same thing. I don't want to use the default service account and I may want to treat PingFederate pods differently from PingDirectory pods to maintain the principal of least privilege. For the Vault use case, I can authorize those service accounts to the appropriate secrets on Vault independently of any cluster action. What I really want is a unique identity for the workload that is also managed by the Helm chart.

The default behavior when I start using Vault is to use a service account called `vault-auth`. This avoids not using the default service account for Vault roles, as recommended, but it requires separate management of that service account. I would end up running a `kubectl apply` with a separate file that's tightly coupled my values.yaml to work around this, which is why I would definitely rather it's just handled by the chart.

The `vault-auth` service account feels like an odd default actually. When using Helm to install Vault, there is no `vault-auth` service account. The service account called `vault-auth` is just called `vault`. This is the service account that has the permission to call the `TokenReview` API that is used by the Vault server. So, it feels weird that the default is either to use a service account that has unnecessary permissions and is designed for a different component or for the installation to fail.

I don't really care about the default behavior though. I just want to have a way to configure the chart to be self-contained. This is already true for the other charts I have to install as setup (like the Vault injector itself).

**Comment by jjustinic** [comment]
To directly address the question about the service account being created with the namespace:
Yes, the `default` service account is created when a namespace is created. However, the recommendation is not to elevate the permissions of the default service account and instead use a unique service account for the workload that can be granted only the required permissions. I might have a `ping` namespace, but could run multiple PingIdentity products in that namespace. I would want the service account used by each one managed by the chart, not speculatively created ahead of time or as a separate process.

**Comment by jjustinic** [comment]
@tsigle Added a PR with an example of the functionality desired to help continue the conversation.

**Comment by tsigle** [comment]
@jjustinic Very helpful with your additional comments and your PR.  I'm going to be getting in release 0.4.4 and will look closer at this, and probably get it in.  I'll reply back here to you if I have additional questions.  Thanks a lot!

**Comment by jjustinic** [comment]
Thanks for the prompt attention @tsigle. I will note that I didn't really expect for the PR to be immediately production ready. I'm perfectly happy if it doesn't make it into the most imminent release and takes a few extra cycles to get something that ultimately serves more use-cases without introducing any concerns.

**Comment by samir-gandhi** [comment]
We have another request for this. Are we still looking to implement this?
Value on new request is that it can be used for assigning permissions from cloud provider to an SA.

**Comment by jjustinic** [comment]
This might not have been the case when this issue was first opened, but currently the basic chart generated from the `helm create` command does exactly what should be needed for these use cases.

There's probably a couple modifications necessary to make it align with the `global` vs. specific product merging done in this chart, but you can see how it works. It falls back to the `default` service account created with the namespace in absence of another value, but generates a relevant name (or allows an override) if it is desired to create one for the specific release. This allows only the necessary permissions to be assigned for the specific workload whether it be for the cloud provider's IAM, Vault access, K8s API access, or anything else.

**Comment by topijag** [comment]
This is definitely something needed!
At the moment we have to create an extra ServiceAccount with the AWS arn annotation needed and patch the deployments after the helm install. Is an extra step that takes time and can be avoided if we can add it in the helm chart.

**Comment by henryrecker-pingidentity** [comment]
In the latest release we've added support for RBAC including generating service accounts. See the release notes - https://helm.pingidentity.com/release-notes/currentRelease/
